# Generated by Django 3.2 on 2022-01-23 02:20

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('sharesite', '0002_submission_one_wordle'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='secret',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
