# Generated by Django 3.2 on 2022-01-23 03:49

from django.db import migrations

def add_wordles(apps, schema_editor):
    # We can't import the Wordle model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    Wordle = apps.get_model('sharesite', 'Wordle')
    with open("sharesite/static/sharesite/words.js", "r") as f:
        words = f.read()[21:-8].replace('"', '').strip().split(", ")[:2315]
        i = 0
        for word in words:
            Wordle.objects.create(day=i, answer=word.upper())
            i += 1
    

class Migration(migrations.Migration):

    dependencies = [
        ('sharesite', '0004_groupmember_one_group'),
    ]

    operations = [
        migrations.RunPython(add_wordles),
    ]
