# Generated by Django 3.2 on 2022-01-24 23:44

from django.db import migrations

def add_profiles(apps, schema_editor):
    # We can't import the Wordle model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    Profile = apps.get_model('sharesite', 'Profile')
    User = apps.get_model('auth', 'User')
    users = User.objects.all()
    for user in users:
        Profile.objects.create(user=user, timezone="America/New_York")

class Migration(migrations.Migration):

    dependencies = [
        ('sharesite', '0006_auto_20220124_1640'),
    ]

    operations = [
        migrations.RunPython(add_profiles),
    ]
