# Generated by Django 3.2 on 2022-01-25 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharesite', '0007_auto_20220124_1844'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='high_contrast',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='groupmember',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='wordle',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
