# Generated by Django 3.2 on 2022-01-26 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sharesite', '0009_submission_statistics'),
    ]

    operations = [
        migrations.RenameField(
            model_name='submission',
            old_name='statistics',
            new_name='statistics_data',
        ),
    ]
