# Generated by Django 3.2 on 2022-01-30 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharesite', '0010_rename_statistics_submission_statistics_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='show_statistics',
            field=models.BooleanField(default=False),
        ),
    ]
