# Generated by Django 3.2 on 2022-01-23 03:49

from django.db import migrations

def update_wordles(apps, schema_editor):
    # We can't import the Wordle model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    Wordle = apps.get_model('sharesite', 'Wordle')
    with open("sharesite/static/sharesite/words.js", "r") as f:
        word_list = f.read()[21:-3].replace('"', '').strip().split(", ")
        words = word_list[:word_list.index("aahed")]
        i = 0
        for word in words:
            w = Wordle.objects.get(day=i)
            w.answer = word.upper()
            w.save()
            i += 1


class Migration(migrations.Migration):

    dependencies = [
        ('sharesite', '0011_profile_show_statistics'),
    ]

    operations = [
        migrations.RunPython(update_wordles),
    ]
